# Generated by Django 3.1.3 on 2023-01-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='grade_point',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
